# Generated by Django 4.1.7 on 2023-02-22 16:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puzzle",
                    models.CharField(default=api.models.generate_puzzle, max_length=16),
                ),
                ("user", models.CharField(max_length=50)),
                ("answer", models.CharField(max_length=16)),
                ("score", models.IntegerField(default=False)),
                ("max_score", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puzzle",
                    models.CharField(default=api.models.generate_puzzle, max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
